apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../namespace.yaml
  - ../../configmap.yaml
  - ../../deployment.yaml
  - ../../service.yaml
  - ../../hpa.yaml

# patch APP_ENV for prod
patches:
  - target:
      kind: ConfigMap
      name: observability-app-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: prod
