services:
  github-runner:
    image: ghcr.io/myoung34/docker-github-actions-runner:latest
    container_name: github-runner
    restart: unless-stopped

    env_file:
      - .env

    environment:
      RUNNER_SCOPE: repo
      RUNNER_NAME: ${RUNNER_NAME:-observability-lab-vm}
      RUNNER_WORKDIR: ${RUNNER_WORKDIR:-/tmp/runner/work}
      LABELS: ${LABELS:-self-hosted,local}
      RUN_AS_ROOT: "true"
      DISABLE_AUTO_UPDATE: "true"
      KUBECONFIG: /kube/config

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runner-data:/tmp/runner
      - /home/vagrant/observability-lab:/home/vagrant/observability-lab
      - /etc/rancher/k3s/k3s.yaml:/kube/config:ro

    network_mode: host
