apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# base resources - overlays patch env-specific values on top of this
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
