#ENC[AES256_GCM,data:9AiD5bMnvnN41J15tzfaV9SaM/dnaBuV2vtSPVWd,iv:WzZuman9PgpRT21tGUvXVGG+iQ3I3tguJLQbH2EhZT8=,tag:g3j2KsX/tVQPv1qEtbyGVg==,type:comment]
grafana_admin_password: ENC[AES256_GCM,data:bf5/r7GBMny/mqR8HfQFaljWtgMRBo2YKWRB/4LLsf0=,iv:O2UfLjTXTjfzGM94VlIiQXJuVbGfeeuv0EHO8ML3Sco=,tag:iSQX58C+f+MfsGBhI1BkjQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/rick0x00-com-1737423573185/locations/global/keyRings/observability-lab-sops/cryptoKeys/observability-lab-key
          created_at: "2026-03-10T17:05:20Z"
          enc: CiQAIBwNVVuFOJhb47HbcFJ5x+z3PpK6TDwvAjllBwMsJxxRJUgSSQC7/wy7Ks1AgpWNG0rqLNG3lLCe1E1Ol33dZABBSdq9N6LOYM2+V3KX2K+FrwuMyHOaM3AyEro3s/7T62PEqSxa0xwF8vfo2t8=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-03-10T17:05:21Z"
    mac: ENC[AES256_GCM,data:phcgCS0HNAoLGHO5I94nNpxH67vcyyrgul/7r0OGTQEsCpcHWW0Wkk5XWrHmcbXdv0Ddfjp36eTPaVjhxQUeGsIECj3XLCz1pR2zl26FHyK8SE6Azos130Gj67Ei6/vXYC8PPCQFoc+LGgwn073FiOOFcyjZFI0jqOV9aN6hssU=,iv:rvaPhV2VwNmmS4/WBU4sxDmVMt0uDBwF8Xtu58vVMoo=,tag:dDtZXxVogaKeZdtble+S/A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
