version: "3"

# lint Dockerfile with hadolint and scripts with shellcheck
tasks:
  default:
    silent: true
    cmds:
      - task --list-all -t "{{.TASKFILE}}"

  docker:
    desc: Lint Dockerfile with hadolint
    cmds:
      - hadolint Dockerfile

  shell:
    desc: Lint shell scripts with shellcheck
    cmds:
      - find var/scripts -type f \( -name "*.sh" -o -name "lab-load" -o -name "lab-validate" \) -print0 | xargs -0 shellcheck --severity=warning
      - find ci/scripts -type f -name "*.sh" -print0 | xargs -0 shellcheck --severity=warning

  all:
    desc: Run all linters
    cmds:
      - task: docker
      - task: shell
